name: GitHub Action Demo
on: push
jobs:
  action-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v7
      - name: Print index.py
        run: cat index.py
      
